### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by GBC-OG** [TheFakeMateo/pokered-clean#2]
This isn't working for me. When I try to build it I get unexpected xor errors in the home.asm file. I managed to fix that by removing the xors. However, then I started getting the following errors in maps.asm:

rgbasm -D _RED -h -o maps_red.o maps.asm
ERROR: maps.asm(229) -> scripts/PowerPlant.asm(10):
    syntax error, unexpected newline
ERROR: maps.asm(366) -> scripts/CeruleanCaveB1F.asm(10):
    syntax error, unexpected newline
ERROR: maps.asm(427) -> scripts/CeladonMart3F.asm(77):
    syntax error, unexpected newline
error: Assembly aborted (3 errors)!
make: *** [Makefile:69: maps_red.o] Error 1

**Comment by JustRegularLuna** [comment]
This repo hasn't been updated in quite a while. It was never updated to the current version of RGBDS and is also lacking a lot of improvements that vanilla pokered has now. At some point I'm just going to write tutorials for the pokered wiki describing the things this was going to do, and remove this unmaintained repo.

**Comment by GBC-OG** [comment]
Is there any chance you would update it? I basically just want to edit the trainers_parties.asm to make new teams for the in game trainers, but I don't know how to do that on vanilla pokered since it doesn't have an option for movesets.

**Comment by JustRegularLuna** [comment]
I may look at it and see about getting it to build on current rgbds. I don't intend to merge all of modern pokered's stuff back into this though.

**Comment by GBC-OG** [comment]
I'd really appreciate it if you could just get it working please. It doesn't need to be updated with all the new stuff from the current rgbds. I've already written a romhack using this disassembly and it kinda sucks that I can't put it together now....

**Comment by GBC-OG** [comment]
> I may look at it and see about getting it to build on current rgbds. I don't intend to merge all of modern pokered's stuff back into this though.

I'd really appreciate it if you could get it working please. It doesn't need to be updated with all the new stuff, it just needs to build the rom. I've already written a romhack using this disassembly with edited trainer teams, learnsets and mart items and it kinda sucks that I can't put it together now....

**Comment by GBC-OG** [comment]
Figured out how to fix it. They were syntax errors, I've proposed the changes here on github. The rom should build fine now.

**Comment by JustRegularLuna** [comment]
glad you got it sorted
